title: Przepisy
description: Książka kucharska
theme: jekyll-theme-minimal
logo: /assets/img/sushi.svg
logo_raster: /assets/img/sushi.png
logo_source: Freepik Stories
show_downloads: false
google_analytics: UA-634071-21
author: Krzysztof Goliński
lang: pl_PL
dirs:
  - title: Zupy
    name: /zupy/
  - title: Dania główne
    name: /dania_glowne/
  - title: Dodatki
    name: /dodatki/
  - title: Desery
    name: /desery/
  - title: Przetwory
    name: /przetwory/
  - title: Notatki
    name: /notatki/